// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved
function pG(Xf,Fi)
{return (Xf==0)?'':' '+Fi+'="'+Xf+'"';}function qG(x,X,i,L,h,W,m,n,H)
{L=kB(L);if(X)
uG(x,H);x.document.write('<a href="'+lB(h,i) +'" target="'+W+'" '+nA+'onmouseout="self.status=\'\';return true;">');x.document.write('<img src="'+L+'"'+pG(m,'width')+pG(n,'height')+' border="0" id="Ads_img'+Ads_iid+'" name="Ads_img'+Ads_iid+'" alt="'+H+'"></a>');yB(x,i);if(X)
vG(x);bB='';cB=0;}function rG(x,X,i,F,h,W,m,n,H,J,K,Ca,Q)
{var Gi=bC(i,'&rdm='+Ads_Timestamp,'');if(X)
uG(x,H);h=lB(h,Gi);K=lB(K,Gi);F=sA[Ads_sec]+'/dat/bgf/'+F;J=sA[Ads_sec]+'/dat/bgf/'+J;gB=h;hB=lB('',Gi);var Hi=F+'?clickTag='+escape(h)+'&url='+escape(h);cC(1,'Flash-Url',Hi);var Jb;if(Q<=fC(1))
{x.document.write('<OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http'+((Ads_sec==1)?'s':'')+'://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=3,0,0,0" id=banner'+pG(m,'width')+pG(n,'height')+'">');x.document.write('<PARAM NAME=movie VALUE="'+Hi+'"><PARAM NAME=play VALUE=true><PARAM NAME=autoplay VALUE=true><PARAM NAME=wmode VALUE=opaque><PARAM NAME=quality VALUE=autohigh><PARAM name=scale value=exactfit>');x.document.write('<EMBED src="'+Hi+'" quality=autohigh autoplay=true play=true wmode=opaque scale=exactfit swLiveConnect=TRUE'+pG(m,'width')+pG(n,'height')+' TYPE="application/x-shockwave-flash" PLUGINSPAGE="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash"></EMBED></OBJECT>');}else
{x.document.write('<a href="'+K+'" target="'+W+'" '+nA+' onmouseout="self.status=\'\';return true;"><img src="'+J+'"'+pG(m,'width')+pG(n,'height')+' border="0" alt="'+H+'"></a>');}yB(x,i);if(X)
vG(x);bB='';cB=0;}function sG(x,X,i,j,k,C,Da,m,n,T,U,A,Ia,Ii)
{var F=pA[Ads_sec]+Ia+dC((Ii>0)?Ii:((T==0)?k:T));var Ji,Te;iid=Ads_iid;bid=k;rdm=uB(j,k,C);if(X||((Da||A)&&zA))
{var Ki='*';for(Te=1;Te<Ads_MultiUrl.length;Te++)
{h=Ads_MultiUrl[Te];Ki+=h.substring(Ads_CountUrl.length,h.length)+'*';}Ji=Ads_wid+'#'+Ads_iid+'#'+j+'#'+k+'#'+Ads_xwid+'#'+Ads_xiid+'#'+Ads_wrd+'#'+Ads_prf+'#'+Ads_par+'#'+Ads_Timestamp+'#'+rdm+'#'+(qA[Ads_sec]+'/red?cmd=url&'+(jA?'flg=1&':''))+'#'+Ads_LinkUrl+'#'+Ki+'#'+wB();}if(X&&(U!=''))
{cC(1,'Sidebar',F+'.html?'+escape(Ji));window.open(F+'.html?'+escape(Ji),U);}else if(X)
{cC(1,'Pop',F+'.html?'+escape(Ji));x.location.href=F+'.html?'+escape(Ji);}else if((Da||A)&&zA)
{cC(1,'Ifr',F+'.html?'+escape(Ji));document.write('<iframe src="'+F+'.html?'+escape(Ji)+'" width="'+m+'" height="'+n+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');}else
{cC(1,'Jsc',F+'.js');if(Ii>0)
{yB(x,i);qB(pA[Ads_sec]+'/dat/dlv/afxplay.js');}qB(F+'.js');}bB='';cB=0;}function tG(x,X,i,M,N,Da,m,n,A)
{N=kB(unescape(N));M=kB(unescape(M));cC(1,'Redirect',N+'/'+M);if(X)
x.location.href=M;else
{if(((Da||A)&&zA)||(N==''))
document.write('<iframe src="'+M+'" width="'+m+'" height="'+n+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');else
qB(N);}yB(window,i);bB='';cB=0;}function uG(x,H)
{x.document.open();x.document.write('<html><head><title>'+H+'</title></head><body topmargin="0" leftmargin="0" rightmargin="0" marginwidth="0" marginheight="0"><table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0" align="center"><tr><td valign="middle"><center>');}function vG(x)
{x.document.write('</center></td></tr></table></body></html>');x.document.close();}function wG(m,n,O,P,V,Z,Y,R,Aa,Ba)
{var y='locationbar=no,directories=no,statusbar=no,toolbar=no,location=no,menubar=no,personalbar=no';var Li='Ads_Popup'+Ads_iid;var Mi,Ni;var Oi=0;var Pi=0;if(Z)
{if (xA)
{Oi=10;Pi=30;}else if (yA)
{Oi=20;Pi=35;}y+=',scrollbars=no,resizable=no,width='+(screen.availWidth-Oi)+',height='+(screen.availHeight-Pi)+',screenX=0,screenY=0';if(wA)
y='fullscreen=yes';}else
{if(Aa)
y+=',resizable=yes,width=90,height=70,innerWidth=90,innerHeight=70';else
y+=',resizable=no,width='+m+',height='+n;if(Ba)
y+=',scrollbars=yes';else
y+=',scrollbars=no';if(V==16)
{O=(screen.width-m-25)*O/100;P=(screen.height-n-50)*P/100;}else if(V==24)
{O=(screen.width-m-25)*Math.random();P=(screen.height-n-50)*Math.random();}if (!zA)
y+=",screenX="+O+",screenY="+P;else
y+=",left="+O+",top="+P;}if((Ads_opt&32)>0)
Li+=Math.round(Math.random()*100000);if((Ads_opt&64)>0)
y='locationbar=yes,scrollbars=yes,directories=yes,statusbar=yes,toolbar=yes,location=yes,menubar=yes,personalbar=yes,resizable=yes';cC(1,'PopUp open START','');x=open('',Li,y);cC(1,'PopUp open END','');if(Z&&(!wA))
x.moveTo(0,0);if(Y&&(R==0))
x.blur();else if(Y)
x.setTimeout('window.blur();',R*1000);if(Aa)
mG(x,m,n);return x;}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved
var iD=[];var jD;function kD(Jf,Kf,Lf)
{if(typeof(Jf)=='undefined')
return [];var s,r;var Mf=[];var Nf=Jf.split('x');var Of=Nf[0];var Pf=Kf-Of;var r=Nf.length;for(s=1;s<r;s++)
{Vg=Nf[s].split(':');if(Lf&&(Vg[2]==-1))
Mf[Vg[0]]=[Vg[1],-1];Vg[2]-=Pf;if(Vg[2]>0)
Mf[Vg[0]]=[Vg[1],Vg[2]];}return Mf;}function lD(Mf,Kf)
{var Lb;var Jf=Kf;for(Lb in Mf)
Jf+='x'+Lb+':'+Mf[Lb][0]+':'+Mf[Lb][1];return Jf;}function mD(Qf,Rf)
{while(Qf.length>800)
Qf=Qf.substr(0,Qf.lastIndexOf('#',Qf.length-2)+1);iD[Rf]=Qf;}function nD(Rf,Fb)
{var Sf='111';var Tf='@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`';var r=0;var Uf='#'+Fb+':';var Qf=iD[Rf];var Vf='';var V=Qf.indexOf(Uf);var Wf=new Date();var Xf,Yf,Zf,Ag,Ad;var Bg,Cg,Dg,Eg;if(Qf=='')
Qf='#';if(V>-1)
{Yf=Qf.substr(V+Uf.length,3+Rf);if(V>0)
Vf=Qf.substr(0,V);Xf=Qf.length-V-Uf.length-3-Rf;if(Xf>0)
Vf+=Qf.substr(V+Uf.length+3+Rf,Xf);Qf=Vf;Zf=new Date(Tf.indexOf(Yf.charAt(0))+2000,Tf.indexOf(Yf.charAt(1))-1,Tf.indexOf(Yf.charAt(2)));Wf.setHours(0);Wf.setMinutes(0);Wf.setSeconds(0);Ag=(Wf.getTime()-Zf.getTime())/1000/60/60/24;intAltWTag=(Zf.getDay()==0?7:Zf.getDay());intNeuWTag=(Wf.getDay()==0?7:Wf.getDay());intAltMTag=Zf.getDate();intNeuMTag=Wf.getDate();Sf=((Ag>0.1)?'1':'0')+(((Ag>6)||(intAltWTag>intNeuWTag))?'1':'0')+(((Ag>29)||(intAltMTag>intNeuMTag))?'1':'0');if(Rf==1)
r=Tf.indexOf(Yf.charAt(3));}Yf='#'+Fb+':';Ad=Wf.getYear();if(Ad<1900)
Ad+=1900;Yf+=Tf.charAt(Ad-2000);Yf+=Tf.charAt(Wf.getMonth()+1);Yf+=Tf.charAt(Wf.getDate());if(Rf==1)
{r++;if(r>21)
r=21;Yf+=Tf.charAt(r);Sf+=Tf.charAt(r);}Qf=Yf+Qf;mD(Qf,Rf);return Sf;}function oD(Uf,Rf,Fg)
{var Ka,La,Xf,Gg,Hg;var Qf=iD[Rf];var Vf='';var Ig='';var Jg=-1;if(Qf=='')
Qf='#';Uf='#'+Uf+'-';Ka=Qf.indexOf(Uf);if(Ka!=-1)
La=Qf.indexOf('#',Ka+1);if((Ka!=-1)&&(La!=1))
{Gg=Qf.substring(Ka+Uf.length,La);if(Ka>0)
Vf=Qf.substr(0,Ka);Xf=Qf.length-La;if(Xf>0)
Vf+=Qf.substr(La,Xf);Qf=Vf;if(Rf==6)
{Hg=Gg.split('-');Ig=Hg[0];Gg=Hg[1];}Jg=Fg-parseInt(Gg,10);if(Jg>1200)
Jg=-1;}iD[Rf]=Qf;return [Jg,Ig];}function pD(j)
{var Kg=new Date();var Jg=Kg.getHours()*60*60+Kg.getMinutes()*60+Kg.getSeconds();var Lg,Mg;Lg=oD(Ads_wid,6,Jg);Mg=oD(j,5,Jg);var Ng=(Lg[0]==-1);var Og=(Mg[0]==-1);var Pg=(Ng?'1':'0')+(Og?'1':'0');if(!Ng)
Pg+=aC(Lg[0],4)+Lg[1];mD('#'+Ads_wid+'-'+Ads_iid+'-'+Jg+iD[6],6);mD('#'+j+'-'+Jg+iD[5],5);return Pg;}function qD()
{iA=sB();cC(2,'Read Cookies');var s,Qg,Lb,Rg,Sg,Tg,Ug,Vg,Rf;var Ha=document.cookie;var Lf=(Ha.toLowerCase().indexOf('sestest')>-1);document.cookie=iA+'SESTEST=1'+tB(-1);var Wg=Ha.split(';');var r=Wg.length;var Eb=new Date();jD=Math.round(Eb.getTime()/1000/60);iD=['','',[],'','','','',[],[],[],0];for(s=0;s<r;s++)
{Rf=-1;Tg=Wg[s].split('=');Lb=Tg[0];Sg=Tg[1];if(Lb.charAt(0)==' ')
Lb=Lb.substr(1,Lb.length-1);if(Lb.substr(0,iA.length)==iA)
Rg=Lb.substring(iA.length,Lb.length);else
Rg='';if(Rg=='KIDYMD')
iD[1]=Sg;else if(Rg=='WIDYMD')
iD[0]=Sg;else if(Lb=='BSUID')
iD[3]=Sg;else if(Lb=='BNDWDT')
iD[4]=Sg;else if(Lb=='BNDLVL')
iD[10]=Sg;else if(Rg=='VISKAM')
iD[5]=Sg;else if(Rg=='VISWEB')
iD[6]=Sg;else if(Rg=='FRQSTR')
{Tg=Sg.split(',');cC(1,'KID',Tg[0]);cC(1,'WID',Tg[1]);cC(1,'NID',Tg[2]);cC(1,'BID',Tg[3]);iD[2]=kD(Tg[0],jD,Lf);iD[7]=kD(Tg[1],jD,Lf);iD[8]=kD(Tg[2],jD,Lf);iD[9]=kD(Tg[3],jD,Lf);}}if(Ads_uid!='')
{Wg=Ads_userdata.split(';');r=Wg.length;iD[2]=[];for(s=1;s<(r-1);s++)
{Tg=Wg[s].split(',');iD[2][Tg[0]]=[Tg[1],1];}}if(iD[3]=='1')
kA=true;cC(1,'KIDYMD',iD[1]);cC(1,'WIDYMD',iD[0]);cC(1,'BSUID' ,iD[3]);cC(1,'BNDWDT',iD[4]);cC(1,'BNDLVL',iD[10]);cC(1,'VISKAM',iD[5]);cC(1,'VISWEB',iD[6]);}function rD(j,Ic)
{var Xg,Yg,Vc,Zg;var Ah='';iA=sB();var Bh=KAS[Ic][4][5];if(KAS[Ic][4][4]>0)
Ah=tB(Bh);else if((KAS[Ic][5]&1)>0)
{Ah=tB(20);Bh=20;}if(Ah!='')
{Vc=parseInt(tD(j,2)+1,10);if(Ads_uid!='')
{Xg=Ads_userdata.split(';'+j+',');if(Xg.length==2)
{Yg=Ads_userdata.split(','+j+';');Ads_userdata=Xg[0]+';'+Yg[1];}Ads_userdata+=j+','+Vc+','+Bh+','+j+';';Zg=new Image();Zg.src='http://uboot.as-eu.falkag.net/usr?cmd=write&id='+Ads_uid+'&data='+Ads_userdata+'&rdm='+Math.random();cC(1,'tp','?cmd=write&id='+Ads_uid+'&data='+Ads_userdata+'&rdm='+Math.random());}else
uD(j,2,Vc,Bh);}}function sD(j,Ic,k,w,Ch)
{iA=sB();var C,Ha;rD(j,Ic);if(k>0)
{if(BAS[w][2][4]>0)
uD(k,9,tD(k,9)+1,BAS[w][2][5]);}if(((KAS[Ic][4][22]&1)>0)&&(IAS[4]>0))
uD(Ads_wid,7,tD(Ads_wid,7)+1,IAS[5]);if(((KAS[Ic][4][22]&2)>0)&&(IAS[6]>0))
uD(Ads_nid,8,tD(Ads_nid,8)+1,IAS[7]);Ha=lD(iD[2],jD)+',' +lD(iD[7],jD)+',' +lD(iD[8],jD)+',' +lD(iD[9],jD);document.cookie=iA+'FRQSTR='+Ha+tB(60*24*365);C=nD(1,j);C='&bls3='+C.substr(0,3)+nD(0,Ads_wid)+C.substr(3,1);document.cookie=iA+'WIDYMD='+iD[0]+tB(60*24*30);document.cookie=iA+'KIDYMD='+iD[1]+tB(60*24*30);C+='&bls4='+pD(j);document.cookie=iA+'VISKAM='+iD[5]+tB(20);document.cookie=iA+'VISWEB='+iD[6]+tB(20);if(kA)
C+='&uid=1';return C;}function tD(Fb,Id)
{if(typeof(iD[Id][''+Fb+''])!='undefined')
return parseInt(iD[Id][''+Fb+''],10);else
return 0;}function uD(Fb,Id,Vc,Bh)
{if(typeof(iD[Id][''+Fb+''])!='undefined')
iD[Id][''+Fb+''][0]=Vc;else
iD[Id][''+Fb+'']=[Vc,Bh];}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved
function kC(Tb,Ub)
{cC(1,'Select-Value',Ub);var s=0;var r=Tb.length;if(r==0)
return -1;while((s<r-1)&&(Ub>Tb[s][1]))
{Ub-=Tb[s][1];s++;}return Tb[s][0];}function lC(Vb,Wb,Xb)
{var s,Yb,Zb,Ac;cC(1,'---- CLOSE OLD PRIORITY','');cC(1,'share-sum of all successfully campaigns',Vb);cC(1,'free shares before this priority',Xb);if(Vb>Xb)
{Yb=Xb/Vb;for(s=Wb;s<uA.length;s++)
uA[s][1]*=Yb;Vb=Xb;}Xb-=Vb;cC(1,'free shares after this priority',Xb);return Xb;}function mC()
{cC(0,'campaign-filtering');var Bc,Cc,Dc,Ec,Fc;var Gc=-2;var Hc=KAS.length;var Xb=100;var Ic,j,Ac,Jc,Kc,Lc,Mc,Nc,Oc;var Vb;var Wb;uA=[];for (Ic=0;Ic<Hc;Ic++)
{Fc=((KAS[Ic][5]&2)>0);if(KAS[Ic][2]!=Gc)
{if(Gc!=-2)
Xb=lC(Vb,Wb,Xb);Gc=KAS[Ic][2];cC(1,'---- START NEW PRIORITY',Gc);Vb=0;Wb=uA.length;}cC(1,'<b>campaign '+KAS[Ic][0]+'</b>',KAS[Ic]);Jc=KAS[Ic][8];Kc=KAS[Ic][10];Lc=IAS[10];if((Lc-Kc)>0)
Jc=Jc*Lc/(Lc-Kc);Ac=KAS[Ic][1];if(Jc<=0)
Jc=Ac;Mc=(Ac/Jc-1)*2+1;if((Mc>10)||(Mc<0.1))
Mc=1;Nc=KAS[Ic][3];Ac=Ac*Mc*100/((Nc==0)?100:Nc);if(isNaN(Ac))
Ac=0;Ec=KAS[Ic][4];Bc=dD(Ec,0,KAS[Ic][0]);Dc=false;if(Ec.length>0)
{Dc=((Ec[0]==0)&&!((Ec[2]==0)&&(Ec[3]==1439)));Cc=(!Dc||bD(Ec[2],Ec[3]));if(Dc)
Ac=Ac*100/KAS[Ic][9];if(Bc&&!Cc&&!Fc)
bA+='9'+KAS[Ic][0]+'-';Bc=(Bc&&Cc);}if((KAS[Ic][5]&8)>0)
Ac=KAS[Ic][1];cC(1,'timetargeting,successful',(Dc)+','+(Cc));if(Fc&&Bc)
{cC(2,'<font color=#ff8000>testcase successful</font>');j=KAS[Ic][0];cA+=j+'-';rD(j,Ic);}else if(Bc)
{cC(2,'<font color=#008000>successful</font>');uA[uA.length]=[Ic,Ac,Dc,Ac];Vb+=Ac;}else
{cC(2,'<font color=#ff0000>failed</font>');}}Xb=lC(Vb,Wb,Xb);}function nC()
{mC();var Pc,Ic,s,Ac;var Hc=uA.length;var Qc=0;cC(0,'campaign-selection');for (Ic=0;Ic<Hc;Ic++)
{s=uA[Ic][0];Ac=uA[Ic][1];Pc=Math.round(Ac/uA[Ic][3]*10)-1;if(Pc>9)
Pc=9;if((Pc>0)&&(KAS[s][0]>0))
bA+=Pc+''+KAS[s][0]+'-';Qc+=Ac;cC(1,'Campaign,Chance,ShareActual,Share,ShareNew',KAS[s][0]+' ,'+KAS[s][3]+' ,'+KAS[s][8]+' ,'+KAS[s][1]+' ,'+Ac);}cC(1,'Chances',bA);return kC(uA,Qc*Math.random());}function oC(Ic,j)
{var Rc=[];var Sc=BAS.length;var Tc=((KAS[Ic][5]&1)>0);var Qc=0;var w,Ac,Uc,Vc,Wc,Xc;var Yc=true;for (w=0;w<Sc;w++)
{cC(1,'<b>Banner '+BAS[w][0]+'</b>',BAS[w]);strInhalt=BAS[w][21];Xc=((strInhalt.length<3)||(strInhalt.indexOf('#'+Ads_iid+'#')>-1));if(((Ads_xl>1)||(Ads_yl>1))&&((BAS[w][13]>1)||(BAS[w][14]>1)))
{Yc=((Ads_xl==BAS[w][13])&&(Ads_yl==BAS[w][14]));cC(1,'Bannersize',Yc);}if(Yc&&Xc&&dD(BAS[w][2],1,BAS[w][0]))
{Ac=BAS[w][1];cC(2,'<font color=#008000>successful</font></b>,Anteil:'+Ac+'<b>');Rc[Rc.length]=[w,Ac];Qc+=Ac;}else
{cC(2,'<font color=#ff0000>failed</font>');}}Sc=Rc.length;if(Tc)
{Vc=tD(j,2);if(Sc>0)
w=Rc[Vc%Sc][0];else
w=-1;}else
w=kC(Rc,Qc*Math.random());return w;}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved
var pC=false;var qC;var rC;var sC=0;function tC(Zc)
{return aC(Zc.getHours(),2)+':'+aC(Zc.getMinutes(),2)+':'+aC(Zc.getSeconds(),2);}function uC(Zc)
{var Ad=Zc.getYear();if(Ad<1900)
Ad+=1900;return aC(Ad,4)+'-'+aC(Zc.getMonth()+1,2)+'-'+aC(Zc.getDate(),2);}function vC()
{if(pC)
return;var Bd,Cd,Dd,s,Ed;var Fd=new Date();var Gd=new Date();Gd.setTime(Fd-0+parseInt(Ads_T[9],10));Bd=iD[1].split('#');Cd=Bd.length-1;Dd=',';for(s=1;s<Cd;s++)
{Ed=Bd[s].split(':');Dd+=Ed[0]+',';}pC=true;qC=';keyword='+escape(Ads_wrd) +';user-domain='+Ads_T[5] +';user-ip='+Ads_T[6] +';url='+escape(window.location.href) +';referrer='+escape(document.referrer) +';accept-language='+escape(Ads_T[7]) +';accept-charset='+escape(Ads_T[8]) +';user-agent='+escape(navigator.userAgent) +';browser-name='+escape(navigator.appName) +';browser-version='+escape(navigator.appVersion) +';flash-version='+fC(0) +';user-day='+(Fd.getDay()==0?7:Fd.getDay()) +';user-time='+tC(Fd) +';user-date='+uC(Fd) +';server-day='+(Gd.getDay()==0?7:Gd.getDay()) +';server-time='+tC(Gd) +';server-date='+uC(Gd) +';campaigns='+Dd +';';if(navigator.appVersion.substring(0,1)>'3')
qC+='java='+(navigator.javaEnabled()?'1':'0') +';screen-width='+screen.width +';screen-height='+screen.height +';window-width='+(window.innerWidth?window.innerWidth:document.body.clientWidth) +';window-height='+(window.innerWidth?window.innerHeight:document.body.clientHeight) +';color-depth='+screen.colorDepth +';';cC(1,'Environment values',qC);}function wC(Hd,r,Fb,Id,Jd,Kd)
{var Ld;if((r>0)&&(Hd>0))
{Ld=((tD(Fb,Id)<r));if((Ld?1:0)==Jd)
return Jd;rC[Kd]=Ld;}return 2;}function xC(Md,Nd,Od,Jd,Kd)
{var Ld;if(Md.length>1)
{Ld=(Md.indexOf('#'+Nd+'#')!=-1);Ld=Od>0?!Ld:Ld;if((Ld?1:0)==Jd)
return Jd;rC[Kd]=Ld;}return 2;}function yC(Md,Od,Jd,Pd,Kd)
{if(Md=='')
return 2;var s,Ab,Qd,Rd,Sd,Td,Ud,Vd,Wd;var Xd='!"%&\'()*+,-./:;<=>?@[\\]^{|}~§ ';var Ld=false;Md=Md.substr(1,Md.length-2);var Ec=Md.split('#');var r=Ec.length;if(r>0)
{if(Pd)
{Ab='';Td=Ads_wrd.length;for(s=0;s<Td;s++)
{Sd=Ads_wrd.charAt(s);if(Xd.indexOf(Sd)!=-1)
Sd='#';Ab+=Sd;}Ab='#'+Ab.toLowerCase()+'#';Qd=Ab;}else
{Ab='#'+Ads_T[5]+'#';Qd='#'+Ads_T[6]+'#';}for(s=0;(s<r)&&(Ld==false);s++)
{Vd=Ec[s].toLowerCase();Ud=false;if(Vd.substring(0,1)=='$')
{Vd=Vd.substring(1,Vd.length-1);Ud=true;}Rd=false;Wd=Ab;if(Vd.substring(0,1)=='!')
{Vd=Vd.substring(1,Vd.length-1);Wd=Qd;Rd=true;}if(Pd)
Vd='#'+Vd;if(!Rd)
Vd+='#';Ld=(Wd.indexOf(Vd)!=-1);if(Ud&&Ld)
{Ld=false;s=r;}}Ld=Od>0?!Ld:Ld;if((Ld?1:0)==Jd)
return Jd;rC[Kd]=Ld;}return 2;}function zC(Yd,Zd)
{var Ae=[];var Be=0;var s,Ce;var r=Yd.length;for(s=0;s<r;s++)
{Ce=Yd[s];if(Ce>=0)
{Ae[Be]=Zd[Ce];Be++;}else if(Ce==-2)
{Be--;Ae[Be-1]=(Ae[Be-1]&&Ae[Be]);}else if(Ce==-4)
{Be--;Ae[Be-1]=(Ae[Be-1]||Ae[Be]);}else if(Ce==-3)
Ae[Be-1]=(!Ae[Be-1]);}return Ae[Be-1];}function aD(Ec,De,Od,Ee,Fe,Jd,Kd)
{var Ld,Lb,Ge,He,Ie,Je,G,Ke;var Le,Me;var s=0;var r=Ec.length;var Zd=[];var Ne=De.toLowerCase();for(s=0;s<r;s++)
{Lb=Ec[s][0];Ge=Ec[s][1];G=Ec[s][2];Ke=Ec[s][3];cC(1,'Profile/Environment -> Name,WishedValue,Type,Operator',Lb+','+Ge+','+G+','+Ke);Le=Ne.indexOf(';'+Lb+'=');if(Le>-1)
{Me=De.indexOf(';',Le+1);if(Me>Le)
Je=unescape(De.substring(Le+2+Lb.length,Me));else
Je='';if(G==5)
G=1;if(G==1)
He=0;else
He='';if((Ke==9)||(Ke==10))
{Ie=Ge.split(';');if(Ie.length==2)
{Ge=Ie[0];He=Ie[1];}else
Ke=0;}if(G==1)
{Je=parseFloat(Je);Ge=parseFloat(Ge);He=parseFloat(He);}if((Ke>5)&&(Ke<9))
{Je=Je.toLowerCase();Ge=Ge.toLowerCase();}if(Ke==0)
Ld=(Je==Ge)
else if(Ke==1)
Ld=(Je!=Ge)
else if(Ke==2)
Ld=(Je<Ge)
else if(Ke==3)
Ld=(Je<=Ge)
else if(Ke==4)
Ld=(Je>Ge)
else if(Ke==5)
Ld=(Je>=Ge)
else if(Ke==6)
Ld=(Je.indexOf(Ge)>-1);else if(Ke==7)
Ld=(Je.indexOf(Ge)<0);else if(Ke==8)
Ld=Je.substr(0,Ge.length-1)==Ge;else if(Ke==9)
Ld=((Je>=Ge)&&(Je<=He))
else if(Ke==10)
Ld=((Je<Ge)||(Je>He))
}else
{Ld=false;}cC(1,'Profile/Environment -> result',Ld);if(Ee==2)
Zd[s]=Ld;else
{if((Ld&&(Ee==1))||(!Ld&&(Ee==0)))
s=r;}}if(Ee==2)
Ld=zC(Fe,Zd);Ld=Od>0?!Ld:Ld;if((Ld?1:0)==Jd)
return Jd;rC[Kd]=Ld;return 2;}function bD(Oe,Pe)
{var Fd=new Date();var Gd=new Date();Gd.setTime(Fd-0+parseInt(Ads_T[9],10));var Qe=Gd.getHours()*60+Gd.getMinutes();if(Oe<Pe)
Ld=((Qe>=Oe)&&(Qe<=Pe));else
Ld=((Qe>=Oe)||(Qe<=Pe));return Ld;}function cD(Re,Se)
{var r=Re.length;var Te;if(typeof(Re.Ads_klist)=='string')
Se+=Re.Ads_klist+'#';for(Te=0;Te<r;Te++)
{try
{Se=cD(Re.frames[Te],Se);}catch(objError) {}}return Se;}function dD(Ec,G,Fb)
{var Jd=Ec[0];var Od=Ec[1];var Ld,Ue,Ve,We,Xe,Dd,Bd,Cd,s,Ye,Ze,Af,Bf;rC=[true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true];if(Ec.length==0)
return true;cC(1,'Targeting',Ec);if(((Jd>0)||(G==1))&&!((Jd==1)&&(Ec[2]==0)&&(Ec[3]==1439)))
{Ld=bD(Ec[2],Ec[3]);cC(1,'Time',Ld);if((Ld?1:0)==Jd)
return Ld;rC[0]=Ld;}Ue=wC(1,Ec[4],Fb,(G==0)?2:9,Jd,1);cC(1,'Frequency (Max:'+Ec[4]+',actual:'+tD(Fb,(G==0)?2:9)+')',Ue!=0);if(Ue<2)
return Ue==1;if(G==0)
{Ue=wC(Ec[22]&1,IAS[4],Ads_wid,7,Jd,12);cC(1,'Frequency (WebSite)',Ue!=0);if(Ue<2)
return Ue==1;Ue=wC(Ec[22]&2,IAS[6],Ads_nid,8,Jd,13);cC(1,'Frequency (Network)',Ue!=0);if(Ue<2)
return Ue==1;}Ue=xC(Ec[6],Ads_T[0],Od&1,Jd,2);cC(1,'OS',Ue!=0);if(Ue<2)
return Ue==1;Ue=xC(Ec[7],Ads_T[1],Od&2,Jd,3);cC(1,'Browser',Ue!=0);if(Ue<2)
return Ue==1;Ue=xC(Ec[8],Ads_T[2],Od&4,Jd,4);cC(1,'Country',Ue!=0);if(Ue<2)
return Ue==1;Ue=xC(Ec[9],Ads_T[3],Od&8,Jd,5);cC(1,'Provider',Ue!=0);if(Ue<2)
return Ue==1;Ue=xC(Ec[26],Ads_T[12],Od&1024,Jd,16);cC(1,'DMA',Ue!=0);if(Ue<2)
return Ue==1;if(Ec[10].length>1)
{Ld=((Ec[10].indexOf('#'+Ads_T[4]+'#')!=-1)||(Ec[10].indexOf('#%'+Ads_T[10]+'#')!=-1)||(Ec[10].indexOf('#$'+Ads_T[11]+'#')!=-1));if((Ads_nid==7)&&(Ads_T[4]<1)&&(Ec[10].indexOf('#$14658#')!=-1)) Ld=true;Ld=(Od&16)>0?!Ld:Ld;cC(1,'Region',Ld);if((Ld?1:0)==Jd)
return Jd;rC[6]=Ld;}Ue=yC(Ec[11],Od&32,Jd,false,7);cC(1,'Domain',Ue!=0);if(Ue<2)
return Ue==1;Ue=yC(Ec[12],Od&64,Jd,true,8);cC(1,'Keyword',Ue!=0);if(Ue<2)
return Ue==1;if(Ec[13].length>0)
{Ue=aD(Ec[13],';'+Ads_prf+';',Od&128,Ec[15],Ec[17],Jd,9);cC(1,'Profile',Ue!=0);if(Ue<2)
return Ue==1;}if(Ec[14].length>0)
{vC();Ue=aD(Ec[14],qC,Od&256,Ec[16],Ec[18],Jd,10);cC(1,'Environment',Ue!=0);if(Ue<2)
return Ue==1;}intBwdLevel=0;Ua=Ec[27];intBwdUser=iD[10];intBwdIP=Ads_T[13];if (Ua==1){eD();intBwdLevel=intBwdUser;}if (Ua==2){intBwdLevel=intBwdIP;}if (Ua==3){eD();intBwdLevel=((intBwdIP>intBwdUser)&&(intBwdUser!=0))?intBwdUser:intBwdIP;}if (Ua==4){eD();intBwdLevel=(intBwdIP>intBwdUser)?intBwdIP:intBwdUser;}if((Ua==5)&&(intBwdUser==intBwdIP))
{ eD();intBwdLevel=intBwdIP;}Ue=xC(Ec[28],intBwdLevel,Od&512,Jd,11);cC(1,'Bandwidth',Ue!=0);if(Ue<2)
return Ue==1;Bf=Ec[23];if((G==0)&&(Bf>0))
{Dd=Ec[24];if(Dd.length>2)
Dd=Dd.substring(1,Dd.length-1);Bd=Dd.split('#');Cd=Bd.length;Ye=-1;cC(1,'vor fngetklist','ok');strKList='#'+cD(top,'');cC(1,'nach fngetklist','ok');for(s=0;(s<Cd)&&(Ye<0);s++)
{Ze=(strKList.indexOf('#'+Bd[s]+'#')>-1);if((Ze?1:4)==Bf)
Ye=0;if((Ze?3:2)==Bf)
Ye=1;}if(Ye<0)
Ye=((Bf==1)||(Bf==4))?1:0;cC(1,'showed Camppaigns,In/Exclude',strKList+','+(Ye==1));if(Ye==Jd)
return (Ye==1);rC[14]=(Ye==1);}s=Ec[25];if(s>0)
{Ze=IAS[8].indexOf('#'+s+':');if(Ze!=-1)
{Ze=IAS[8].indexOf(':',Ze);Af=IAS[8].indexOf('#',Ze);Ze=IAS[8].substring(Ze+1,Af);Af=Ads_fcount[s];if(typeOf(Af)=='undefined')
Af=0;Ld=Ze>Af;cC(1,'Family',Ld);if((Ld?1:0)==Jd)
return Ld;rC[15]=Ld;}}if(Jd!=2)
return (Jd==0);else
return zC(Ec[19],rC);}function eD()
{if((sC==0)&&kA&&(document.cookie.toLowerCase().indexOf('bndlvl')==-1))
sC=1;}function fD()
{if(sC!=1)
return;if((fC(1)<6)||yA)
{cC(1,'Start BW-Test','Java');document.write('<applet codebase="'+tA[Ads_sec]+'/" code="bandwidth.class" id="bandwidth" name="bandwidth" width="0" height="0" mayscript="MAYSCRIPT"><param name="cbfunc" value="gD"></applet>');}else
{cC(1,'Start BW-Test','Flash');var Ra=window.location.hostname;document.write('<scr'+'ipt for="Ads_BWD" event="FSCommand(Ef,Ff)" language="VBScript"> \n on error resume next \n call Ads_BWD_DoFSCommand(Ef,Ff) \n </scr'+'ipt\>');document.write('<object id="Ads_BWD" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab" width="1" height="1">');document.write('<param name=movie value="'+tA[Ads_sec]+'/dat/dlv/bwdetect.swf?domain='+Ra+'&path='+tA[Ads_sec]+'"><param name=play value=true><param name=autoplay value=true>');document.write('<embed name="Ads_BWD" id="Ads_BWD" src="'+tA[Ads_sec]+'/dat/dlv/bwdetect.swf?domain='+Ra+'&path='+tA[Ads_sec]+'" play=true autoplay=true swLiveConnect=true width="1" height="1" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash">');document.write('</embed></object>');}sC=2;}function gD(Cf)
{var Df=0;Cf*=8;document.cookie='BNDWDT='+Cf+tB(60*24*7);if(Cf==0)
Df=0;else if(Cf<9)
Df=1;else if(Cf<33)
Df=2;else if(Cf<65)
Df=3;else if(Cf<129)
Df=4;else if(Cf<385)
Df=5;else if(Cf<769)
Df=6;else if(Cf<1501)
Df=7;else if(Cf<3001)
Df=8;else
Df=9;document.cookie='BNDLVL='+Df+tB(60*24*7);}function Ads_BWD_DoFSCommand(Ef,Ff)
{gD(Ff/8);}function hD()
{var Gf=new Date();document.writeln('<scr'+'ipt language="Javascript"><!--');document.writeln('oA=new Date();');document.writeln('/'+'/--></scr'+'ipt><scr'+'ipt language="Javascript" src="'+tA[Ads_sec]+'/dat/dlv/aslprebwd.js?'+Gf.getTime()+'0"></scr'+'ipt>');}function Ads_PreBandwidth()
{var Hf=new Date();var If=Math.round((8026/((Hf.getTime()-oA.getTime()+1)/1000))/1024);cC(1,'Pre BW-Test',If);gD(If);SAS();}